---
sidebar: sidebar 
permalink: ONTAP/update-storage-system.html 
keywords: update ontap storage system 
summary: Aktualisieren Sie Ihr ONTAP -Speichersystem, um die neuen und verbesserten Funktionen zu nutzen. 
---
= Das ONTAP Update in den Software-Updates initiieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die ONTAP Zielversion identifiziert und alle Blocker behoben und bestätigt haben, können Sie nun mit der Aktualisierung Ihres ONTAP Speichersystems beginnen.

.Schritte
. Wählen Sie in der linken Navigationsleiste der Konsole *Health* > *Software-Updates* aus.
+
Die Liste der Cluster, die ein Software-Update benötigen, wird angezeigt.

. Ermitteln Sie die ONTAP-Zielversion für Ihr Speichersystem.
+
Informationen zur Ermittlung der ONTAP Zielversion finden Sie unter link:../ONTAP/choose-ontap-910-later.html["ONTAP Versionen mit Software-Updates vergleichen"].

. Beheben und bestätigen Sie die ONTAP Blocker.
+
Informationen zur Behebung von Blockern finden Sie unter link:../ONTAP/fix-blockers-warnings.html["ONTAP Blocker und Warnungen mit Software-Updates beheben"].

. Lesen und akzeptieren Sie die Endbenutzer-Lizenzvereinbarung.
+
Warten Sie, bis das ONTAP Image abgerufen wurde.

. Klicken Sie auf *Update installieren*, um den Aktualisierungsvorgang abzuschließen.

